#!/bin/sh
#
#    Copyright (C) 2018-2021 Yaroslav Pronin <proninyaroslav@mail.ru>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

# Usage abrowser_deb2rpm [-p DEB_FILE_PATH] [-r RELEASE_VERSION]

BASE_URL="http://archive.trisquel.info/trisquel/pool/main/f/firefox/"

RELEASE_FILE="abrowser_93.0+build1-0ubuntu0.20.04.1+10.0trisquel83_amd64.deb"

while getopts "p:r:" OPTION || :; do
    case $OPTION in
        p) DEB_FILE=${OPTARG};;
        r) RELEASE_VER=${OPTARG};;
		[?]) break;;
    esac
done

if [[ -z "$DEB_FILE" ]]; then
	DEB_FILE=$RELEASE_FILE
	curl -O "$BASE_URL$DEB_FILE"
fi

RPM=$(sudo alien -r -c "$DEB_FILE")
RPM=${RPM%' generated'}

rpmrebuild -p \
	   --directory=. \
	   --release=$RELEASE_VER \
	   --change-spec-whole='sed -e "\|Requires:      libxul.so.*|d
\|%dir %attr(0755, root, root) \"/\"|d
\|%dir %attr(0755, root, root) \"/etc\"|d
\|%dir %attr(0755, root, root) \"/etc/apparmor.d\"|d
\|%dir %attr(0755, root, root) \"/etc/apparmor.d/disable\"|d
\|%config %attr(0644, root, root) \"/etc/apparmor.d/usr.bin.abrowser\"|d
\|%dir %attr(0755, root, root) \"/etc/apport\"|d
\|%dir %attr(0755, root, root) \"/etc/apport/blacklist.d\"|d
\|%config %attr(0644, root, root) \"/etc/apport/blacklist.d/abrowser\"|d
\|%dir %attr(0755, root, root) \"/etc/apport/native-origins.d\"|d
\|%config %attr(0644, root, root) \"/etc/apport/native-origins.d/abrowser\"|d
\|%dir %attr(0755, root, root) \"/usr\"|d
\|%dir %attr(0755, root, root) \"/usr/bin\"|d
\|%dir %attr(0755, root, root) \"/usr/lib\"|d
\|%dir %attr(0755, root, root) \"/usr/lib/.build-id.*\"|d
\|%dir %attr(0755, root, root) \"/usr/share\"|d
\|%dir %attr(0755, root, root) \"/usr/share/applications\"|d
\|%dir %attr(0755, root, root) \"/usr/share/apport\"|d
\|%dir %attr(0755, root, root) \"/usr/share/apport/package-hooks\"|d
\|%attr(0644, root, root) \"/usr/share/apport/package-hooks/source_abrowser.py\"|d
\|%dir %attr(0755, root, root) \"/usr/share/doc\"|d
\|%dir %attr(0755, root, root) \"/usr/share/icons\"|d
\|%dir %attr(0755, root, root) \"/usr/share/icons/hicolor\"|d
\|%dir %attr(0755, root, root) \"/usr/share/icons/hicolor/128x128\"|d
\|%dir %attr(0755, root, root) \"/usr/share/icons/hicolor/128x128/apps\"|d
\|%dir %attr(0755, root, root) \"/usr/share/icons/hicolor/symbolic\"|d
\|%dir %attr(0755, root, root) \"/usr/share/icons/hicolor/symbolic/apps\"|d
\|%dir %attr(0755, root, root) \"/usr/share/lintian\"|d
\|%dir %attr(0755, root, root) \"/usr/share/lintian/overrides\"|d
\|%attr(0644, root, root) \"/usr/share/lintian/overrides/abrowser\"|d
\|%dir %attr(0755, root, root) \"/usr/share/man\"|d
\|%dir %attr(0755, root, root) \"/usr/share/man/man1\"|d"' \
	   "$RPM"

rm -f "$RPM"
